export const ALL_PERMISSIONS = [
  {
    module: "EMPLOYEE",
    sub_module: "EMPLOYEE",
    action: "CREATE",
    key_name: "EMPLOYEE.EMPLOYEE.CREATE",
    description: "Create employee",
  },
  {
    module: "EMPLOYEE",
    sub_module: "EMPLOYEE",
    action: "READ",
    key_name: "EMPLOYEE.EMPLOYEE.READ",
    description: "Read employee",
  },
  {
    module: "EMPLOYEE",
    sub_module: "EMPLOYEE",
    action: "UPDATE",
    key_name: "EMPLOYEE.EMPLOYEE.UPDATE",
    description: "Update employee",
  },
  {
    module: "EMPLOYEE",
    sub_module: "EMPLOYEE",
    action: "DELETE",
    key_name: "EMPLOYEE.EMPLOYEE.DELETE",
    description: "Delete employee",
  },
  {
    module: "EMPLOYEE",
    sub_module: "DEPARTMENT",
    action: "CREATE",
    key_name: "EMPLOYEE.DEPARTMENT.CREATE",
    description: "Create department",
  },
  {
    module: "EMPLOYEE",
    sub_module: "DEPARTMENT",
    action: "READ",
    key_name: "EMPLOYEE.DEPARTMENT.READ",
    description: "Read departments",
  },
  {
    module: "EMPLOYEE",
    sub_module: "DEPARTMENT",
    action: "UPDATE",
    key_name: "EMPLOYEE.DEPARTMENT.UPDATE",
    description: "Update department",
  },
  {
    module: "EMPLOYEE",
    sub_module: "DEPARTMENT",
    action: "DELETE",
    key_name: "EMPLOYEE.DEPARTMENT.DELETE",
    description: "Delete department",
  },
  {
    module: "EMPLOYEE",
    sub_module: "DESIGNATION",
    action: "CREATE",
    key_name: "EMPLOYEE.DESIGNATION.CREATE",
    description: "Create designation",
  },
  {
    module: "EMPLOYEE",
    sub_module: "DESIGNATION",
    action: "READ",
    key_name: "EMPLOYEE.DESIGNATION.READ",
    description: "Read designations",
  },
  {
    module: "EMPLOYEE",
    sub_module: "DESIGNATION",
    action: "UPDATE",
    key_name: "EMPLOYEE.DESIGNATION.UPDATE",
    description: "Update designation",
  },
  {
    module: "EMPLOYEE",
    sub_module: "DESIGNATION",
    action: "DELETE",
    key_name: "EMPLOYEE.DESIGNATION.DELETE",
    description: "Delete designation",
  },
  {
    module: "EMPLOYEE",
    sub_module: "EMPLOYEE_TYPE",
    action: "CREATE",
    key_name: "EMPLOYEE.EMPLOYEE_TYPE.CREATE",
    description: "Create employee type",
  },
  {
    module: "EMPLOYEE",
    sub_module: "EMPLOYEE_TYPE",
    action: "READ",
    key_name: "EMPLOYEE.EMPLOYEE_TYPE.READ",
    description: "Read employee types",
  },
  {
    module: "EMPLOYEE",
    sub_module: "EMPLOYEE_TYPE",
    action: "UPDATE",
    key_name: "EMPLOYEE.EMPLOYEE_TYPE.UPDATE",
    description: "Update employee type",
  },
  {
    module: "EMPLOYEE",
    sub_module: "EMPLOYEE_TYPE",
    action: "DELETE",
    key_name: "EMPLOYEE.EMPLOYEE_TYPE.DELETE",
    description: "Delete employee type",
  },
  {
    module: "EMPLOYEE",
    sub_module: "DUTY_SHIFT",
    action: "CREATE",
    key_name: "EMPLOYEE.DUTY_SHIFT.CREATE",
    description: "Create duty shift",
  },
  {
    module: "EMPLOYEE",
    sub_module: "DUTY_SHIFT",
    action: "READ",
    key_name: "EMPLOYEE.DUTY_SHIFT.READ",
    description: "Read duty shifts",
  },
  {
    module: "EMPLOYEE",
    sub_module: "DUTY_SHIFT",
    action: "UPDATE",
    key_name: "EMPLOYEE.DUTY_SHIFT.UPDATE",
    description: "Update duty shift",
  },
  {
    module: "EMPLOYEE",
    sub_module: "DUTY_SHIFT",
    action: "DELETE",
    key_name: "EMPLOYEE.DUTY_SHIFT.DELETE",
    description: "Delete duty shift",
  },
  {
    module: "EMPLOYEE",
    sub_module: "BANK",
    action: "CREATE",
    key_name: "EMPLOYEE.BANK.CREATE",
    description: "Create bank",
  },
  {
    module: "EMPLOYEE",
    sub_module: "BANK",
    action: "READ",
    key_name: "EMPLOYEE.BANK.READ",
    description: "Read banks",
  },
  {
    module: "EMPLOYEE",
    sub_module: "BANK",
    action: "UPDATE",
    key_name: "EMPLOYEE.BANK.UPDATE",
    description: "Update bank",
  },
  {
    module: "EMPLOYEE",
    sub_module: "BANK",
    action: "DELETE",
    key_name: "EMPLOYEE.BANK.DELETE",
    description: "Delete bank",
  },
  {
    module: "INVENTORY",
    sub_module: "ITEM_TYPE",
    action: "CREATE",
    key_name: "INVENTORY.ITEM_TYPE.CREATE",
    description: "Create item type",
  },
  {
    module: "INVENTORY",
    sub_module: "ITEM_TYPE",
    action: "READ",
    key_name: "INVENTORY.ITEM_TYPE.READ",
    description: "Read item types",
  },
  {
    module: "INVENTORY",
    sub_module: "ITEM_TYPE",
    action: "UPDATE",
    key_name: "INVENTORY.ITEM_TYPE.UPDATE",
    description: "Update item type",
  },
  {
    module: "INVENTORY",
    sub_module: "ITEM_TYPE",
    action: "DELETE",
    key_name: "INVENTORY.ITEM_TYPE.DELETE",
    description: "Delete item type",
  },
  {
    module: "INVENTORY",
    sub_module: "CATEGORY",
    action: "CREATE",
    key_name: "INVENTORY.CATEGORY.CREATE",
    description: "Create category",
  },
  {
    module: "INVENTORY",
    sub_module: "CATEGORY",
    action: "READ",
    key_name: "INVENTORY.CATEGORY.READ",
    description: "Read categories",
  },
  {
    module: "INVENTORY",
    sub_module: "CATEGORY",
    action: "UPDATE",
    key_name: "INVENTORY.CATEGORY.UPDATE",
    description: "Update category",
  },
  {
    module: "INVENTORY",
    sub_module: "CATEGORY",
    action: "DELETE",
    key_name: "INVENTORY.CATEGORY.DELETE",
    description: "Delete category",
  },
  {
    module: "INVENTORY",
    sub_module: "SUB_CATEGORY",
    action: "CREATE",
    key_name: "INVENTORY.SUB_CATEGORY.CREATE",
    description: "Create sub category",
  },
  {
    module: "INVENTORY",
    sub_module: "SUB_CATEGORY",
    action: "READ",
    key_name: "INVENTORY.SUB_CATEGORY.READ",
    description: "Read sub categories",
  },
  {
    module: "INVENTORY",
    sub_module: "SUB_CATEGORY",
    action: "UPDATE",
    key_name: "INVENTORY.SUB_CATEGORY.UPDATE",
    description: "Update sub category",
  },
  {
    module: "INVENTORY",
    sub_module: "SUB_CATEGORY",
    action: "DELETE",
    key_name: "INVENTORY.SUB_CATEGORY.DELETE",
    description: "Delete sub category",
  },
  {
    module: "INVENTORY",
    sub_module: "MANUFACTURER",
    action: "CREATE",
    key_name: "INVENTORY.MANUFACTURER.CREATE",
    description: "Create manufacturer",
  },
  {
    module: "INVENTORY",
    sub_module: "MANUFACTURER",
    action: "READ",
    key_name: "INVENTORY.MANUFACTURER.READ",
    description: "Read manufacturers",
  },
  {
    module: "INVENTORY",
    sub_module: "MANUFACTURER",
    action: "UPDATE",
    key_name: "INVENTORY.MANUFACTURER.UPDATE",
    description: "Update manufacturer",
  },
  {
    module: "INVENTORY",
    sub_module: "MANUFACTURER",
    action: "DELETE",
    key_name: "INVENTORY.MANUFACTURER.DELETE",
    description: "Delete manufacturer",
  },
  {
    module: "INVENTORY",
    sub_module: "UNIT",
    action: "CREATE",
    key_name: "INVENTORY.UNIT.CREATE",
    description: "Create unit",
  },
  {
    module: "INVENTORY",
    sub_module: "UNIT",
    action: "READ",
    key_name: "INVENTORY.UNIT.READ",
    description: "Read units",
  },
  {
    module: "INVENTORY",
    sub_module: "UNIT",
    action: "UPDATE",
    key_name: "INVENTORY.UNIT.UPDATE",
    description: "Update unit",
  },
  {
    module: "INVENTORY",
    sub_module: "UNIT",
    action: "DELETE",
    key_name: "INVENTORY.UNIT.DELETE",
    description: "Delete unit",
  },
  {
    module: "INVENTORY",
    sub_module: "LOCATION",
    action: "CREATE",
    key_name: "INVENTORY.LOCATION.CREATE",
    description: "Create location",
  },
  {
    module: "INVENTORY",
    sub_module: "LOCATION",
    action: "READ",
    key_name: "INVENTORY.LOCATION.READ",
    description: "Read locations",
  },
  {
    module: "INVENTORY",
    sub_module: "LOCATION",
    action: "UPDATE",
    key_name: "INVENTORY.LOCATION.UPDATE",
    description: "Update location",
  },
  {
    module: "INVENTORY",
    sub_module: "LOCATION",
    action: "DELETE",
    key_name: "INVENTORY.LOCATION.DELETE",
    description: "Delete location",
  },
  {
    module: "INVENTORY",
    sub_module: "SUPPLIER",
    action: "CREATE",
    key_name: "INVENTORY.SUPPLIER.CREATE",
    description: "Create supplier",
  },
  {
    module: "INVENTORY",
    sub_module: "SUPPLIER",
    action: "READ",
    key_name: "INVENTORY.SUPPLIER.READ",
    description: "Read suppliers",
  },
  {
    module: "INVENTORY",
    sub_module: "SUPPLIER",
    action: "UPDATE",
    key_name: "INVENTORY.SUPPLIER.UPDATE",
    description: "Update supplier",
  },
  {
    module: "INVENTORY",
    sub_module: "SUPPLIER",
    action: "DELETE",
    key_name: "INVENTORY.SUPPLIER.DELETE",
    description: "Delete supplier",
  },
  {
    module: "INVENTORY",
    sub_module: "ITEM_DEFINITION",
    action: "CREATE",
    key_name: "INVENTORY.ITEM_DEFINITION.CREATE",
    description: "Create item definition",
  },
  {
    module: "INVENTORY",
    sub_module: "ITEM_DEFINITION",
    action: "READ",
    key_name: "INVENTORY.ITEM_DEFINITION.READ",
    description: "Read item definitions",
  },
  {
    module: "INVENTORY",
    sub_module: "ITEM_DEFINITION",
    action: "UPDATE",
    key_name: "INVENTORY.ITEM_DEFINITION.UPDATE",
    description: "Update item definition",
  },
  {
    module: "INVENTORY",
    sub_module: "ITEM_DEFINITION",
    action: "DELETE",
    key_name: "INVENTORY.ITEM_DEFINITION.DELETE",
    description: "Delete item definition",
  },
  {
    module: "INVENTORY",
    sub_module: "OPENING_STOCK",
    action: "READ",
    key_name: "INVENTORY.OPENING_STOCK.READ",
    description: "Read opening stock",
  },
  {
    module: "INVENTORY",
    sub_module: "OPENING_STOCK",
    action: "UPDATE",
    key_name: "INVENTORY.OPENING_STOCK.UPDATE",
    description: "Update opening stock",
  },
  {
    module: "INVENTORY",
    sub_module: "ITEM_REPORT",
    action: "READ",
    key_name: "INVENTORY.ITEM_REPORT.READ",
    description: "Read item report",
  },
  {
    module: "ACCESS",
    sub_module: "USERS",
    action: "CREATE",
    key_name: "ACCESS.USERS.CREATE",
    description: "Create user",
  },
  {
    module: "ACCESS",
    sub_module: "USERS",
    action: "READ",
    key_name: "ACCESS.USERS.READ",
    description: "Read user",
  },
  {
    module: "ACCESS",
    sub_module: "USERS",
    action: "UPDATE",
    key_name: "ACCESS.USERS.UPDATE",
    description: "Update user",
  },
  {
    module: "ACCESS",
    sub_module: "USERS",
    action: "DELETE",
    key_name: "ACCESS.USERS.DELETE",
    description: "Delete user",
  },
  {
    module: "ACCESS",
    sub_module: "USERS",
    action: "ASSIGN",
    key_name: "ACCESS.USERS.ASSIGN",
    description: "Assign group to user",
  },
  {
    module: "ACCESS",
    sub_module: "GROUPS",
    action: "CREATE",
    key_name: "ACCESS.GROUPS.CREATE",
    description: "Create group",
  },
  {
    module: "ACCESS",
    sub_module: "GROUPS",
    action: "READ",
    key_name: "ACCESS.GROUPS.READ",
    description: "Read groups",
  },
  {
    module: "ACCESS",
    sub_module: "PERMISSIONS",
    action: "CREATE",
    key_name: "ACCESS.PERMISSIONS.CREATE",
    description: "Create permission",
  },
  {
    module: "ACCESS",
    sub_module: "PERMISSIONS",
    action: "READ",
    key_name: "ACCESS.PERMISSIONS.READ",
    description: "Read permissions",
  },
  {
    module: "ACCESS",
    sub_module: "PERMISSIONS",
    action: "ASSIGN",
    key_name: "ACCESS.PERMISSIONS.ASSIGN",
    description: "Assign permission to group",
  },
  {
    module: "SETUP",
    sub_module: "COMPANY",
    action: "READ",
    key_name: "SETUP.COMPANY.READ",
    description: "Read company profile",
  },
  {
    module: "SETUP",
    sub_module: "COMPANY",
    action: "UPDATE",
    key_name: "SETUP.COMPANY.UPDATE",
    description: "Update company profile",
  },
];
