ALTER TABLE suppliers
  ADD COLUMN IF NOT EXISTS supplier_code VARCHAR(50) NULL UNIQUE AFTER id,
  ADD COLUMN IF NOT EXISTS contact_person VARCHAR(255) NULL AFTER supplier_name,
  ADD COLUMN IF NOT EXISTS city VARCHAR(150) NULL AFTER contact_person,
  ADD COLUMN IF NOT EXISTS mobile_number VARCHAR(50) NULL AFTER city,
  ADD COLUMN IF NOT EXISTS email VARCHAR(255) NULL AFTER phone,
  ADD COLUMN IF NOT EXISTS opening_balance DECIMAL(12, 2) NOT NULL DEFAULT 0 AFTER address,
  ADD COLUMN IF NOT EXISTS ob_date DATE NULL AFTER opening_balance;
