CREATE TABLE IF NOT EXISTS quotations (
  id                  INT AUTO_INCREMENT PRIMARY KEY,
  quotation_no        VARCHAR(30)    NOT NULL,
  quotation_date      DATE           NOT NULL,
  revision_id         VARCHAR(20)    NOT NULL UNIQUE,
  base_revision_id    VARCHAR(20)    NOT NULL,
  revision_no         INT            NOT NULL DEFAULT 0,
  parent_quotation_id INT            DEFAULT NULL,
  is_revision         TINYINT(1)     NOT NULL DEFAULT 0,
  customer_id         INT            NOT NULL,
  customer_name       VARCHAR(255)   DEFAULT NULL,
  person              VARCHAR(255)   DEFAULT NULL,
  designation         VARCHAR(255)   DEFAULT NULL,
  department          VARCHAR(255)   DEFAULT NULL,
  estimation_id       VARCHAR(30)    DEFAULT NULL,
  service_id          INT            DEFAULT NULL,
  service_name        VARCHAR(255)   DEFAULT NULL,
  letter_type         ENUM('Letter','Quotation','Bill','Invoice') NOT NULL DEFAULT 'Quotation',
  tax_mode            ENUM('withTax','withoutTax') NOT NULL,
  print_template      VARCHAR(80)    NOT NULL DEFAULT 'executive_letterhead',
  created_by          INT            DEFAULT NULL,
  total_qty           DECIMAL(15,2)  NOT NULL DEFAULT 0,
  sub_total           DECIMAL(15,2)  NOT NULL DEFAULT 0,
  gst_total           DECIMAL(15,2)  NOT NULL DEFAULT 0,
  grand_total         DECIMAL(15,2)  NOT NULL DEFAULT 0,
  status              ENUM('active','inactive') NOT NULL DEFAULT 'active',
  created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_quotations_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE RESTRICT,
  CONSTRAINT fk_quotations_service FOREIGN KEY (service_id) REFERENCES services(id) ON DELETE SET NULL,
  CONSTRAINT fk_quotations_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_quotations_parent FOREIGN KEY (parent_quotation_id) REFERENCES quotations(id) ON DELETE SET NULL,
  KEY idx_quotations_no (quotation_no),
  KEY idx_quotations_revision (base_revision_id, revision_no),
  KEY idx_quotations_customer (customer_id),
  KEY idx_quotations_status (status)
);

CREATE TABLE IF NOT EXISTS quotation_items (
  id             INT AUTO_INCREMENT PRIMARY KEY,
  quotation_id   INT            NOT NULL,
  item_rate_id   INT            DEFAULT NULL,
  item_name      VARCHAR(255)   DEFAULT NULL,
  rate           DECIMAL(15,2)  NOT NULL DEFAULT 0,
  qty            DECIMAL(15,2)  NOT NULL DEFAULT 0,
  description    TEXT           DEFAULT NULL,
  total          DECIMAL(15,2)  NOT NULL DEFAULT 0,
  gst_percent    DECIMAL(5,2)   NOT NULL DEFAULT 0,
  gst_amount     DECIMAL(15,2)  NOT NULL DEFAULT 0,
  rate_with_gst  DECIMAL(15,2)  NOT NULL DEFAULT 0,
  total_with_gst DECIMAL(15,2)  NOT NULL DEFAULT 0,
  created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_quotation_items_quotation FOREIGN KEY (quotation_id) REFERENCES quotations(id) ON DELETE CASCADE,
  CONSTRAINT fk_quotation_items_item_rate FOREIGN KEY (item_rate_id) REFERENCES item_rates(id) ON DELETE SET NULL,
  KEY idx_quotation_items_quotation (quotation_id)
);
