CREATE TABLE IF NOT EXISTS estimations (
  id                   INT AUTO_INCREMENT PRIMARY KEY,
  estimate_id          VARCHAR(20)    NOT NULL UNIQUE,
  estimate_date        DATE           NOT NULL,
  customer_id          INT            DEFAULT NULL,
  person               VARCHAR(255)   DEFAULT NULL,
  designation          VARCHAR(255)   DEFAULT NULL,
  service_id           INT            DEFAULT NULL,
  created_by           INT            DEFAULT NULL,
  grand_purchase_total DECIMAL(15,2)  NOT NULL DEFAULT 0,
  grand_sale_total     DECIMAL(15,2)  NOT NULL DEFAULT 0,
  grand_discount_total DECIMAL(15,2)  NOT NULL DEFAULT 0,
  grand_final_total    DECIMAL(15,2)  NOT NULL DEFAULT 0,
  status               ENUM('active','inactive') NOT NULL DEFAULT 'active',
  created_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_estimation_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
  CONSTRAINT fk_estimation_service  FOREIGN KEY (service_id)  REFERENCES services(id)  ON DELETE SET NULL,
  CONSTRAINT fk_estimation_user     FOREIGN KEY (created_by)  REFERENCES users(id)     ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS estimation_items (
  id                  INT AUTO_INCREMENT PRIMARY KEY,
  estimation_id       INT            NOT NULL,
  item_rate_id        INT            DEFAULT NULL,
  item_name           VARCHAR(255)   DEFAULT NULL,
  qty                 DECIMAL(10,2)  NOT NULL DEFAULT 0,
  description         TEXT           DEFAULT NULL,
  purchase_price      DECIMAL(15,2)  NOT NULL DEFAULT 0,
  purchase_total      DECIMAL(15,2)  NOT NULL DEFAULT 0,
  sale_price          DECIMAL(15,2)  NOT NULL DEFAULT 0,
  sale_total          DECIMAL(15,2)  NOT NULL DEFAULT 0,
  sale_price_with_tax DECIMAL(15,2)  NOT NULL DEFAULT 0,
  sale_total_with_tax DECIMAL(15,2)  NOT NULL DEFAULT 0,
  discount_percent    DECIMAL(5,2)   NOT NULL DEFAULT 0,
  discount_amount     DECIMAL(15,2)  NOT NULL DEFAULT 0,
  final_price         DECIMAL(15,2)  NOT NULL DEFAULT 0,
  final_total         DECIMAL(15,2)  NOT NULL DEFAULT 0,
  created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_estimation_items_estimation FOREIGN KEY (estimation_id) REFERENCES estimations(id) ON DELETE CASCADE,
  CONSTRAINT fk_estimation_items_item_rate  FOREIGN KEY (item_rate_id)  REFERENCES item_rates(id)  ON DELETE SET NULL
);
