CREATE TABLE IF NOT EXISTS item_definitions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  item_code VARCHAR(100) NOT NULL,
  primary_barcode VARCHAR(255) DEFAULT NULL,
  secondary_barcode VARCHAR(255) DEFAULT NULL,
  item_type_id INT NOT NULL,
  category_id INT NOT NULL,
  sub_category_id INT DEFAULT NULL,
  manufacturer_id INT DEFAULT NULL,
  supplier_id INT DEFAULT NULL,
  item_name VARCHAR(255) NOT NULL,
  unit_id INT NOT NULL,
  unit_qty DECIMAL(12, 2) NOT NULL DEFAULT 0,
  stock DECIMAL(12, 2) NOT NULL DEFAULT 0,
  reorder_level INT NOT NULL DEFAULT 0,
  location_id INT DEFAULT NULL,
  purchase_price DECIMAL(12, 2) NOT NULL DEFAULT 0,
  sale_price DECIMAL(12, 2) NOT NULL DEFAULT 0,
  is_expirable TINYINT(1) NOT NULL DEFAULT 0,
  expiry_days INT DEFAULT NULL,
  is_cost_item TINYINT(1) NOT NULL DEFAULT 0,
  stop_sale TINYINT(1) NOT NULL DEFAULT 0,
  image VARCHAR(255) DEFAULT NULL,
  status ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_item_code (item_code),
  UNIQUE KEY unique_primary_barcode (primary_barcode),
  UNIQUE KEY unique_secondary_barcode (secondary_barcode),
  KEY idx_item_definitions_item_name (item_name),
  FOREIGN KEY (item_type_id) REFERENCES item_types(id) ON DELETE RESTRICT,
  FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE RESTRICT,
  FOREIGN KEY (sub_category_id) REFERENCES sub_categories(id) ON DELETE SET NULL,
  FOREIGN KEY (manufacturer_id) REFERENCES manufacturers(id) ON DELETE SET NULL,
  FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL,
  FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE RESTRICT,
  FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE SET NULL
);
