CREATE TABLE IF NOT EXISTS item_rates (
  id INT AUTO_INCREMENT PRIMARY KEY,
  rate_date DATE NOT NULL,
  supplier_id INT NOT NULL,
  quotation_id VARCHAR(100) DEFAULT NULL,
  category_id INT NOT NULL,
  sub_category_id INT DEFAULT NULL,
  manufacturer_id INT DEFAULT NULL,
  item_definition_id INT NOT NULL,
  item_specification TEXT DEFAULT NULL,
  currency ENUM('PKR', 'USD') NOT NULL DEFAULT 'PKR',
  exchange_rate DECIMAL(12, 4) NOT NULL DEFAULT 1,
  reseller_price_usd DECIMAL(12, 2) NOT NULL DEFAULT 0,
  reseller_price DECIMAL(12, 2) NOT NULL DEFAULT 0,
  sale_price DECIMAL(12, 2) NOT NULL DEFAULT 0,
  sales_tax_percent DECIMAL(5, 2) NOT NULL DEFAULT 0,
  sales_tax_amount DECIMAL(12, 2) NOT NULL DEFAULT 0,
  i_tax_percent DECIMAL(5, 2) NOT NULL DEFAULT 0,
  i_tax_amount DECIMAL(12, 2) NOT NULL DEFAULT 0,
  other_tax_percent DECIMAL(5, 2) NOT NULL DEFAULT 0,
  other_tax_amount DECIMAL(12, 2) NOT NULL DEFAULT 0,
  profit_percent DECIMAL(5, 2) NOT NULL DEFAULT 0,
  profit_amount DECIMAL(12, 2) NOT NULL DEFAULT 0,
  sale_price_with_tax DECIMAL(12, 2) NOT NULL DEFAULT 0,
  status ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_item_rates_supplier_id (supplier_id),
  KEY idx_item_rates_item_definition_id (item_definition_id),
  KEY idx_item_rates_rate_date (rate_date),
  FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT,
  FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE RESTRICT,
  FOREIGN KEY (sub_category_id) REFERENCES sub_categories(id) ON DELETE SET NULL,
  FOREIGN KEY (manufacturer_id) REFERENCES manufacturers(id) ON DELETE SET NULL,
  FOREIGN KEY (item_definition_id) REFERENCES item_definitions(id) ON DELETE CASCADE
);
