CREATE TABLE IF NOT EXISTS suppliers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  supplier_code VARCHAR(50) UNIQUE DEFAULT NULL,
  supplier_name VARCHAR(255) NOT NULL,
  contact_person VARCHAR(255) DEFAULT NULL,
  city VARCHAR(150) DEFAULT NULL,
  mobile_number VARCHAR(50) DEFAULT NULL,
  phone VARCHAR(50) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  address TEXT DEFAULT NULL,
  opening_balance DECIMAL(12, 2) NOT NULL DEFAULT 0,
  ob_date DATE DEFAULT NULL,
  status ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_supplier_name (supplier_name)
);
